-- CAP Uniform Inspection Tracker
-- Run this in the Supabase SQL Editor for a new project.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  display_name text not null,
  role text not null default 'inspector' check (role in ('admin', 'inspector')),
  created_at timestamptz not null default now()
);

-- Editable scoring thresholds. These are intentionally data, not hard-coded app logic.
-- Automatically create an application profile when a Supabase Auth user is created.
-- The first Auth user becomes the initial administrator; later users default to inspector.
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  initial_role text;
  initial_name text;
begin
  if exists (select 1 from public.profiles) then
    initial_role := 'inspector';
  else
    initial_role := 'admin';
  end if;

  initial_name := coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), split_part(coalesce(new.email, 'CAP User'), '@', 1));

  insert into public.profiles (id, email, display_name, role)
  values (new.id, coalesce(new.email, new.id::text), initial_name, initial_role)
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

-- If Auth users already existed before this migration, backfill their profiles.
-- The oldest existing Auth user becomes the initial administrator when no profile exists yet.
do $$
begin
  if not exists (select 1 from public.profiles) then
    insert into public.profiles (id, email, display_name, role)
    select u.id,
           coalesce(u.email, u.id::text),
           coalesce(nullif(u.raw_user_meta_data ->> 'display_name', ''), split_part(coalesce(u.email, 'CAP User'), '@', 1)),
           'admin'
    from auth.users u
    order by u.created_at asc
    limit 1
    on conflict (id) do nothing;
  end if;

  insert into public.profiles (id, email, display_name, role)
  select u.id,
         coalesce(u.email, u.id::text),
         coalesce(nullif(u.raw_user_meta_data ->> 'display_name', ''), split_part(coalesce(u.email, 'CAP User'), '@', 1)),
         'inspector'
  from auth.users u
  where not exists (select 1 from public.profiles p where p.id = u.id)
  on conflict (id) do nothing;
end;
$$;

create table if not exists public.grading_rules (
  grade_group text primary key check (grade_group in ('airman', 'nco_officer')),
  passing_min smallint not null check (passing_min between 0 and 10),
  excellent_min smallint not null check (excellent_min between 0 and 10),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id),
  constraint grading_rules_order check (passing_min <= excellent_min)
);

insert into public.grading_rules (grade_group, passing_min, excellent_min)
values
  ('airman', 4, 6),
  ('nco_officer', 5, 8)
on conflict (grade_group) do nothing;

create table if not exists public.cadets (
  id bigint generated by default as identity primary key,
  capid text not null unique,
  name text not null,
  grade text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inspections (
  id bigint generated by default as identity primary key,
  client_uuid uuid unique,
  cadet_id bigint not null references public.cadets(id) on delete cascade,
  inspection_date date not null default current_date,
  grade_at_inspection text not null,
  grade_group text not null check (grade_group in ('airman', 'nco_officer')),
  personal_appearance smallint not null check (personal_appearance between 0 and 2),
  garments smallint not null check (garments between 0 and 2),
  accoutrements smallint not null check (accoutrements between 0 and 2),
  footwear smallint not null check (footwear between 0 and 2),
  military_bearing smallint not null check (military_bearing between 0 and 2),
  total_score smallint not null default 0 check (total_score between 0 and 10),
  overall_rating text not null default 'Needs Improvement' check (overall_rating in ('Needs Improvement', 'Satisfactory', 'Excellent')),
  passed boolean not null default false,
  notes text,
  evaluator_id uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);

create index if not exists inspections_cadet_date_idx on public.inspections(cadet_id, inspection_date desc);
create index if not exists inspections_date_idx on public.inspections(inspection_date desc);

create or replace function public.touch_cadet_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists cadets_touch_updated_at on public.cadets;
create trigger cadets_touch_updated_at
before update on public.cadets
for each row execute function public.touch_cadet_updated_at();

-- Server-side scoring prevents a modified browser from saving a fake total/result.
create or replace function public.calculate_inspection_result()
returns trigger
language plpgsql
as $$
declare
  score_total smallint;
  pass_min smallint;
  excellent_minimum smallint;
begin
  score_total := new.personal_appearance + new.garments + new.accoutrements + new.footwear + new.military_bearing;
  new.total_score := score_total;

  select r.passing_min, r.excellent_min
    into pass_min, excellent_minimum
  from public.grading_rules r
  where r.grade_group = new.grade_group;

  -- Safe fallback if the settings row is ever accidentally missing.
  if pass_min is null or excellent_minimum is null then
    if new.grade_group = 'airman' then
      pass_min := 4;
      excellent_minimum := 6;
    else
      pass_min := 5;
      excellent_minimum := 8;
    end if;
  end if;

  if score_total < pass_min then
    new.overall_rating := 'Needs Improvement';
    new.passed := false;
  elsif score_total < excellent_minimum then
    new.overall_rating := 'Satisfactory';
    new.passed := true;
  else
    new.overall_rating := 'Excellent';
    new.passed := true;
  end if;

  return new;
end;
$$;

drop trigger if exists inspections_calculate_result on public.inspections;
create trigger inspections_calculate_result
before insert or update on public.inspections
for each row execute function public.calculate_inspection_result();

-- Helper used by RLS policies. SECURITY DEFINER avoids recursive profile policy checks.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

alter table public.profiles enable row level security;
alter table public.grading_rules enable row level security;
alter table public.cadets enable row level security;
alter table public.inspections enable row level security;

-- Profiles: users see themselves; admins see all users.
drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles
for select to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists profiles_admin_update on public.profiles;
create policy profiles_admin_update on public.profiles
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Grading rules: all signed-in evaluators can read; only admins can change them.
drop policy if exists grading_rules_select on public.grading_rules;
create policy grading_rules_select on public.grading_rules
for select to authenticated using (true);

drop policy if exists grading_rules_admin_insert on public.grading_rules;
create policy grading_rules_admin_insert on public.grading_rules
for insert to authenticated with check (public.is_admin());

drop policy if exists grading_rules_admin_update on public.grading_rules;
create policy grading_rules_admin_update on public.grading_rules
for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- Cadet roster: authenticated evaluators may view, add, and correct roster details.
drop policy if exists cadets_select on public.cadets;
create policy cadets_select on public.cadets
for select to authenticated using (true);

drop policy if exists cadets_insert on public.cadets;
create policy cadets_insert on public.cadets
for insert to authenticated with check (true);

drop policy if exists cadets_update on public.cadets;
create policy cadets_update on public.cadets
for update to authenticated using (true) with check (true);

drop policy if exists cadets_admin_delete on public.cadets;
create policy cadets_admin_delete on public.cadets
for delete to authenticated using (public.is_admin());

-- Inspections: all authorized evaluators can report; evaluator/admin can correct rows; admin can delete.
drop policy if exists inspections_select on public.inspections;
create policy inspections_select on public.inspections
for select to authenticated using (true);

drop policy if exists inspections_insert on public.inspections;
create policy inspections_insert on public.inspections
for insert to authenticated with check (evaluator_id = auth.uid());

drop policy if exists inspections_update on public.inspections;
create policy inspections_update on public.inspections
for update to authenticated
using (evaluator_id = auth.uid() or public.is_admin())
with check (evaluator_id = auth.uid() or public.is_admin());

drop policy if exists inspections_admin_delete on public.inspections;
create policy inspections_admin_delete on public.inspections
for delete to authenticated using (public.is_admin());

-- Explicit Data API grants. RLS still controls which rows each signed-in user can access.
grant usage on schema public to authenticated;
grant select on public.profiles to authenticated;
grant update on public.profiles to authenticated;
grant select, insert, update on public.grading_rules to authenticated;
grant select, insert, update, delete on public.cadets to authenticated;
grant select, insert, update, delete on public.inspections to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- FIRST ADMIN BOOTSTRAP
-- After this migration is installed, create ONE user in Supabase Dashboard > Authentication > Users.
-- The trigger above automatically creates that user's public.profiles row as role = 'admin'.
-- Every later Auth user defaults to inspector unless an administrator changes/creates it through the app.

-- Multi-unit extension (also applied by migration 20260828234500_multiunit_reporting.sql)
-- Multi-unit support, structured cadet names, unit-aware reporting, and inspector analysis helpers.

create table if not exists public.units (
  id bigint generated by default as identity primary key,
  charter_number text not null unique,
  name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.cadets
  add column if not exists first_name text,
  add column if not exists last_name text,
  add column if not exists current_unit_id bigint references public.units(id);

-- Best-effort split of legacy single-name data. The final word becomes last name;
-- everything before it becomes first name. Administrators/evaluators can correct it later.
update public.cadets
set
  first_name = coalesce(first_name,
    case
      when btrim(name) ~ '\s' then regexp_replace(btrim(name), '\s+[^\s]+$', '')
      else btrim(name)
    end),
  last_name = coalesce(last_name,
    case
      when btrim(name) ~ '\s' then regexp_replace(btrim(name), '^.*\s+', '')
      else ''
    end)
where first_name is null or last_name is null;

alter table public.inspections
  add column if not exists unit_id bigint references public.units(id);

create index if not exists cadets_current_unit_idx on public.cadets(current_unit_id);
create index if not exists cadets_last_first_idx on public.cadets(last_name, first_name);
create index if not exists inspections_unit_date_idx on public.inspections(unit_id, inspection_date desc);
create index if not exists inspections_evaluator_date_idx on public.inspections(evaluator_id, inspection_date desc);

create or replace function public.touch_unit_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists units_touch_updated_at on public.units;
create trigger units_touch_updated_at
before update on public.units
for each row execute function public.touch_unit_updated_at();

-- Keep the legacy name column synchronized for backward compatibility and exports.
create or replace function public.sync_cadet_full_name()
returns trigger
language plpgsql
as $$
begin
  if nullif(btrim(coalesce(new.first_name, '')), '') is not null
     or nullif(btrim(coalesce(new.last_name, '')), '') is not null then
    new.name = btrim(concat_ws(' ', nullif(btrim(new.first_name), ''), nullif(btrim(new.last_name), '')));
  end if;
  return new;
end;
$$;

drop trigger if exists cadets_sync_full_name on public.cadets;
create trigger cadets_sync_full_name
before insert or update of first_name, last_name on public.cadets
for each row execute function public.sync_cadet_full_name();

alter table public.units enable row level security;

drop policy if exists units_select on public.units;
create policy units_select on public.units
for select to authenticated using (true);

drop policy if exists units_admin_insert on public.units;
create policy units_admin_insert on public.units
for insert to authenticated with check (public.is_admin());

drop policy if exists units_admin_update on public.units;
create policy units_admin_update on public.units
for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- Inspector directory exposes only display names/IDs needed by reporting, not emails.
create or replace function public.list_inspectors()
returns table(id uuid, display_name text)
language sql
stable
security definer
set search_path = public
as $$
  select p.id, p.display_name
  from public.profiles p
  order by p.display_name;
$$;

revoke all on function public.list_inspectors() from public;
grant execute on function public.list_inspectors() to authenticated;

-- Lets an administrator place records created before multi-unit support into a real unit.
create or replace function public.assign_unassigned_records(p_unit_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  cadet_count integer := 0;
  inspection_count integer := 0;
begin
  if not public.is_admin() then
    raise exception 'Administrator access required';
  end if;

  if not exists (select 1 from public.units where id = p_unit_id) then
    raise exception 'Unit not found';
  end if;

  update public.cadets
  set current_unit_id = p_unit_id
  where current_unit_id is null;
  get diagnostics cadet_count = row_count;

  update public.inspections
  set unit_id = p_unit_id
  where unit_id is null;
  get diagnostics inspection_count = row_count;

  return jsonb_build_object('cadets', cadet_count, 'inspections', inspection_count);
end;
$$;

revoke all on function public.assign_unassigned_records(bigint) from public;
grant execute on function public.assign_unassigned_records(bigint) to authenticated;

-- Data API privileges for objects created by this later migration. RLS above still
-- decides which rows each signed-in user may read or change.
grant select, insert, update on public.units to authenticated;
grant usage, select on all sequences in schema public to authenticated;

