// Generated by setup-supabase.ps1
window.CAP_APP_CONFIG = {
  mode: "supabase",
  appName: "CAP Uniform Inspection Tracker",
  supabaseUrl: "https://uekiecpijomfhezwllst.supabase.co",
  supabasePublishableKey: "sb_publishable_pdeK6fu4mqyI-Ox9V0lkgg_Bw4Gr_IY"
};
