$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $Root

Write-Host ''
Write-Host 'CAP Uniform Inspection Tracker - Supabase Setup' -ForegroundColor Cyan
Write-Host '------------------------------------------------' -ForegroundColor Cyan
Write-Host 'This will create/update the database schema, RLS policies, scoring rules,'
Write-Host 'deploy the create-user Edge Function, and write config.js for the website.'
Write-Host ''

if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
    throw 'Node.js 20 or newer is required. Install Node.js, then run this setup again.'
}

$nodeVersion = (& node -p "process.versions.node.split('.')[0]").Trim()
if ([int]$nodeVersion -lt 20) {
    throw "Node.js 20 or newer is required. Detected Node.js major version $nodeVersion."
}

$ProjectRef = (Read-Host 'Supabase project reference (the ID in your Supabase dashboard URL)').Trim()
if ([string]::IsNullOrWhiteSpace($ProjectRef)) { throw 'A project reference is required.' }

function Invoke-Supabase {
    param([Parameter(ValueFromRemainingArguments=$true)][string[]]$Args)
    & npx --yes supabase@latest @Args
    if ($LASTEXITCODE -ne 0) { throw "Supabase command failed: $($Args -join ' ')" }
}

Write-Host ''
Write-Host '1/5 Initializing local Supabase project files...' -ForegroundColor Yellow
if (-not (Test-Path (Join-Path $Root 'supabase\config.toml'))) {
    Invoke-Supabase init
} else {
    Write-Host 'supabase/config.toml already exists; keeping it.'
}

Write-Host ''
Write-Host '2/5 Signing in to Supabase CLI...' -ForegroundColor Yellow
Write-Host 'A browser or access-token prompt may appear.'
Invoke-Supabase login

Write-Host ''
Write-Host '3/5 Linking this folder to your Supabase project...' -ForegroundColor Yellow
Write-Host 'Supabase may ask for the database password you chose when creating the project.'
Invoke-Supabase link --project-ref $ProjectRef

Write-Host ''
Write-Host '4/5 Applying database migrations...' -ForegroundColor Yellow
Invoke-Supabase db push

Write-Host ''
Write-Host '5/5 Deploying administrator user-creation function...' -ForegroundColor Yellow
Invoke-Supabase functions deploy create-user --project-ref $ProjectRef --no-verify-jwt

Write-Host ''
$PublishableKey = (Read-Host 'Paste the project PUBLISHABLE key (browser-safe key)').Trim()
if ([string]::IsNullOrWhiteSpace($PublishableKey)) {
    Write-Warning 'No publishable key entered. config.js was not changed.'
} else {
    $ProjectUrl = "https://$ProjectRef.supabase.co"
    $Config = @"
// Generated by setup-supabase.ps1
window.CAP_APP_CONFIG = {
  mode: "supabase",
  appName: "CAP Uniform Inspection Tracker",
  supabaseUrl: "$ProjectUrl",
  supabasePublishableKey: "$PublishableKey"
};
"@
    Set-Content -Path (Join-Path $Root 'config.js') -Value $Config -Encoding UTF8
    Write-Host 'config.js updated for Supabase mode.' -ForegroundColor Green
}

Write-Host ''
Write-Host 'DATABASE SETUP COMPLETE' -ForegroundColor Green
Write-Host ''
Write-Host 'One final account step:' -ForegroundColor Yellow
Write-Host 'Create your FIRST email/password user in Supabase > Authentication > Users.'
Write-Host 'The database automatically makes the first user the application Administrator.'
Write-Host 'No SQL is required. After that, create additional users from the Administration tab.'
Write-Host ''
Write-Host "Authentication page: https://supabase.com/dashboard/project/$ProjectRef/auth/users"
Write-Host ''

$Open = Read-Host 'Open the Supabase Authentication page now? (Y/N)'
if ($Open -match '^[Yy]') {
    Start-Process "https://supabase.com/dashboard/project/$ProjectRef/auth/users"
}
