-- Multi-unit support, structured cadet names, unit-aware reporting, and inspector analysis helpers.

create table if not exists public.units (
  id bigint generated by default as identity primary key,
  charter_number text not null unique,
  name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.cadets
  add column if not exists first_name text,
  add column if not exists last_name text,
  add column if not exists current_unit_id bigint references public.units(id);

-- Best-effort split of legacy single-name data. The final word becomes last name;
-- everything before it becomes first name. Administrators/evaluators can correct it later.
update public.cadets
set
  first_name = coalesce(first_name,
    case
      when btrim(name) ~ '\s' then regexp_replace(btrim(name), '\s+[^\s]+$', '')
      else btrim(name)
    end),
  last_name = coalesce(last_name,
    case
      when btrim(name) ~ '\s' then regexp_replace(btrim(name), '^.*\s+', '')
      else ''
    end)
where first_name is null or last_name is null;

alter table public.inspections
  add column if not exists unit_id bigint references public.units(id);

create index if not exists cadets_current_unit_idx on public.cadets(current_unit_id);
create index if not exists cadets_last_first_idx on public.cadets(last_name, first_name);
create index if not exists inspections_unit_date_idx on public.inspections(unit_id, inspection_date desc);
create index if not exists inspections_evaluator_date_idx on public.inspections(evaluator_id, inspection_date desc);

create or replace function public.touch_unit_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists units_touch_updated_at on public.units;
create trigger units_touch_updated_at
before update on public.units
for each row execute function public.touch_unit_updated_at();

-- Keep the legacy name column synchronized for backward compatibility and exports.
create or replace function public.sync_cadet_full_name()
returns trigger
language plpgsql
as $$
begin
  if nullif(btrim(coalesce(new.first_name, '')), '') is not null
     or nullif(btrim(coalesce(new.last_name, '')), '') is not null then
    new.name = btrim(concat_ws(' ', nullif(btrim(new.first_name), ''), nullif(btrim(new.last_name), '')));
  end if;
  return new;
end;
$$;

drop trigger if exists cadets_sync_full_name on public.cadets;
create trigger cadets_sync_full_name
before insert or update of first_name, last_name on public.cadets
for each row execute function public.sync_cadet_full_name();

alter table public.units enable row level security;

drop policy if exists units_select on public.units;
create policy units_select on public.units
for select to authenticated using (true);

drop policy if exists units_admin_insert on public.units;
create policy units_admin_insert on public.units
for insert to authenticated with check (public.is_admin());

drop policy if exists units_admin_update on public.units;
create policy units_admin_update on public.units
for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- Inspector directory exposes only display names/IDs needed by reporting, not emails.
create or replace function public.list_inspectors()
returns table(id uuid, display_name text)
language sql
stable
security definer
set search_path = public
as $$
  select p.id, p.display_name
  from public.profiles p
  order by p.display_name;
$$;

revoke all on function public.list_inspectors() from public;
grant execute on function public.list_inspectors() to authenticated;

-- Lets an administrator place records created before multi-unit support into a real unit.
create or replace function public.assign_unassigned_records(p_unit_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  cadet_count integer := 0;
  inspection_count integer := 0;
begin
  if not public.is_admin() then
    raise exception 'Administrator access required';
  end if;

  if not exists (select 1 from public.units where id = p_unit_id) then
    raise exception 'Unit not found';
  end if;

  update public.cadets
  set current_unit_id = p_unit_id
  where current_unit_id is null;
  get diagnostics cadet_count = row_count;

  update public.inspections
  set unit_id = p_unit_id
  where unit_id is null;
  get diagnostics inspection_count = row_count;

  return jsonb_build_object('cadets', cadet_count, 'inspections', inspection_count);
end;
$$;

revoke all on function public.assign_unassigned_records(bigint) from public;
grant execute on function public.assign_unassigned_records(bigint) to authenticated;

-- Data API privileges for objects created by this later migration. RLS above still
-- decides which rows each signed-in user may read or change.
grant select, insert, update on public.units to authenticated;
grant usage, select on all sequences in schema public to authenticated;
